image: alpine/edge
packages: [ zola ]
oauth: pages.sr.ht/PAGES:RW
environment:
  site: dokoissho.srht.site
sources:
  - https://git.sr.ht/~dokoissho/zola.386
tasks:
  - build: |
      cd zola.386
      zola build
  - package: |
      cd zola.386
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz