name = "ASMR 4 CATS"
description = "Headphones recommended"
license = "MIT"
homepage = "https://github.com/lopes/zola.386"
min_version = "0.10.1"
demo = "https://zola386.netlify.com"

[author]
name = "Martin Roberts"
homepage = "https://github.com/mroberts1"
